name: Lab 1

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build
      run: |
        cd Lab1/module/
        make
          
    - name: install
      run: |
        cd Lab1/module/
        sudo insmod encrypt.ko
        sudo mknod /dev/encrypt c $(cat /proc/devices | grep encrypt | awk '{print $1}') 0

    - name: test
      run: |
        cd Lab1/test/
        sudo ./test.sh
